name: sms_flutter_plus
description: "A Flutter plugin to send and receive SMS and manage permissions."
version: 1.0.0
homepage: https://github.com/mgh-devs/SMSFlutterPlugin
repository: https://github.com/mgh-devs/SMSFlutterPlugin

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mgh.sms_flutter
        pluginClass: SmsFlutterPlugin
